/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as SetupLandingRouteImport } from './routes/setup-landing'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WizardIndexRouteImport } from './routes/wizard.index'
import { Route as WizardSuccessRouteImport } from './routes/wizard.success'
import { Route as WizardReviewRouteImport } from './routes/wizard.review'
import { Route as WizardPositionRouteImport } from './routes/wizard.position'
import { Route as WizardOrgRouteImport } from './routes/wizard.org'
import { Route as WizardFinancialRouteImport } from './routes/wizard.financial'
import { Route as WizardEmployeeRouteImport } from './routes/wizard.employee'
import { Route as WizardCompanyRouteImport } from './routes/wizard.company'
import { Route as WizardChecklistRouteImport } from './routes/wizard.checklist'
import { Route as WizardBranchRouteImport } from './routes/wizard.branch'
import { Route as AuthVerifySentRouteImport } from './routes/auth.verify-sent'
import { Route as AuthVerifyResultRouteImport } from './routes/auth.verify-result'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthEmailRouteImport } from './routes/auth.email'
import { Route as AuthCreatePasswordRouteImport } from './routes/auth.create-password'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWorkflowIndexRouteImport } from './routes/_authenticated/admin.workflow.index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin.templates.index'
import { Route as AuthenticatedAdminSystemIndexRouteImport } from './routes/_authenticated/admin.system.index'
import { Route as AuthenticatedAdminSecurityIndexRouteImport } from './routes/_authenticated/admin.security.index'
import { Route as AuthenticatedAdminReferenceDataIndexRouteImport } from './routes/_authenticated/admin.reference-data.index'
import { Route as AuthenticatedAdminOrganizationIndexRouteImport } from './routes/_authenticated/admin.organization.index'
import { Route as AuthenticatedAdminNumberingIndexRouteImport } from './routes/_authenticated/admin.numbering.index'
import { Route as AuthenticatedAdminMasterDataIndexRouteImport } from './routes/_authenticated/admin.master-data.index'
import { Route as AuthenticatedAdminLanguagesIndexRouteImport } from './routes/_authenticated/admin.languages.index'
import { Route as AuthenticatedAdminBusinessPartnersIndexRouteImport } from './routes/_authenticated/admin.business-partners.index'
import { Route as AuthenticatedAdminReferenceDataSourceIdRouteImport } from './routes/_authenticated/admin.reference-data.$sourceId'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupLandingRoute = SetupLandingRouteImport.update({
  id: '/setup-landing',
  path: '/setup-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardIndexRoute = WizardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WizardRoute,
} as any)
const WizardSuccessRoute = WizardSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => WizardRoute,
} as any)
const WizardReviewRoute = WizardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => WizardRoute,
} as any)
const WizardPositionRoute = WizardPositionRouteImport.update({
  id: '/position',
  path: '/position',
  getParentRoute: () => WizardRoute,
} as any)
const WizardOrgRoute = WizardOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => WizardRoute,
} as any)
const WizardFinancialRoute = WizardFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => WizardRoute,
} as any)
const WizardEmployeeRoute = WizardEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => WizardRoute,
} as any)
const WizardCompanyRoute = WizardCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => WizardRoute,
} as any)
const WizardChecklistRoute = WizardChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => WizardRoute,
} as any)
const WizardBranchRoute = WizardBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => WizardRoute,
} as any)
const AuthVerifySentRoute = AuthVerifySentRouteImport.update({
  id: '/auth/verify-sent',
  path: '/auth/verify-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyResultRoute = AuthVerifyResultRouteImport.update({
  id: '/auth/verify-result',
  path: '/auth/verify-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: '/auth/email',
  path: '/auth/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreatePasswordRoute = AuthCreatePasswordRouteImport.update({
  id: '/auth/create-password',
  path: '/auth/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWorkflowIndexRoute =
  AuthenticatedAdminWorkflowIndexRouteImport.update({
    id: '/workflow/',
    path: '/workflow/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemIndexRoute =
  AuthenticatedAdminSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecurityIndexRoute =
  AuthenticatedAdminSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferenceDataIndexRoute =
  AuthenticatedAdminReferenceDataIndexRouteImport.update({
    id: '/reference-data/',
    path: '/reference-data/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationIndexRoute =
  AuthenticatedAdminOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNumberingIndexRoute =
  AuthenticatedAdminNumberingIndexRouteImport.update({
    id: '/numbering/',
    path: '/numbering/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMasterDataIndexRoute =
  AuthenticatedAdminMasterDataIndexRouteImport.update({
    id: '/master-data/',
    path: '/master-data/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLanguagesIndexRoute =
  AuthenticatedAdminLanguagesIndexRouteImport.update({
    id: '/languages/',
    path: '/languages/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessPartnersIndexRoute =
  AuthenticatedAdminBusinessPartnersIndexRouteImport.update({
    id: '/business-partners/',
    path: '/business-partners/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferenceDataSourceIdRoute =
  AuthenticatedAdminReferenceDataSourceIdRouteImport.update({
    id: '/reference-data/$sourceId',
    path: '/reference-data/$sourceId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/setup-landing': typeof SetupLandingRoute
  '/wizard': typeof WizardRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-result': typeof AuthVerifyResultRoute
  '/auth/verify-sent': typeof AuthVerifySentRoute
  '/wizard/branch': typeof WizardBranchRoute
  '/wizard/checklist': typeof WizardChecklistRoute
  '/wizard/company': typeof WizardCompanyRoute
  '/wizard/employee': typeof WizardEmployeeRoute
  '/wizard/financial': typeof WizardFinancialRoute
  '/wizard/org': typeof WizardOrgRoute
  '/wizard/position': typeof WizardPositionRoute
  '/wizard/review': typeof WizardReviewRoute
  '/wizard/success': typeof WizardSuccessRoute
  '/wizard/': typeof WizardIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/reference-data/$sourceId': typeof AuthenticatedAdminReferenceDataSourceIdRoute
  '/admin/business-partners/': typeof AuthenticatedAdminBusinessPartnersIndexRoute
  '/admin/languages/': typeof AuthenticatedAdminLanguagesIndexRoute
  '/admin/master-data/': typeof AuthenticatedAdminMasterDataIndexRoute
  '/admin/numbering/': typeof AuthenticatedAdminNumberingIndexRoute
  '/admin/organization/': typeof AuthenticatedAdminOrganizationIndexRoute
  '/admin/reference-data/': typeof AuthenticatedAdminReferenceDataIndexRoute
  '/admin/security/': typeof AuthenticatedAdminSecurityIndexRoute
  '/admin/system/': typeof AuthenticatedAdminSystemIndexRoute
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/workflow/': typeof AuthenticatedAdminWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/setup-landing': typeof SetupLandingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-result': typeof AuthVerifyResultRoute
  '/auth/verify-sent': typeof AuthVerifySentRoute
  '/wizard/branch': typeof WizardBranchRoute
  '/wizard/checklist': typeof WizardChecklistRoute
  '/wizard/company': typeof WizardCompanyRoute
  '/wizard/employee': typeof WizardEmployeeRoute
  '/wizard/financial': typeof WizardFinancialRoute
  '/wizard/org': typeof WizardOrgRoute
  '/wizard/position': typeof WizardPositionRoute
  '/wizard/review': typeof WizardReviewRoute
  '/wizard/success': typeof WizardSuccessRoute
  '/wizard': typeof WizardIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/reference-data/$sourceId': typeof AuthenticatedAdminReferenceDataSourceIdRoute
  '/admin/business-partners': typeof AuthenticatedAdminBusinessPartnersIndexRoute
  '/admin/languages': typeof AuthenticatedAdminLanguagesIndexRoute
  '/admin/master-data': typeof AuthenticatedAdminMasterDataIndexRoute
  '/admin/numbering': typeof AuthenticatedAdminNumberingIndexRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationIndexRoute
  '/admin/reference-data': typeof AuthenticatedAdminReferenceDataIndexRoute
  '/admin/security': typeof AuthenticatedAdminSecurityIndexRoute
  '/admin/system': typeof AuthenticatedAdminSystemIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/workflow': typeof AuthenticatedAdminWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/setup-landing': typeof SetupLandingRoute
  '/wizard': typeof WizardRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/create-password': typeof AuthCreatePasswordRoute
  '/auth/email': typeof AuthEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-result': typeof AuthVerifyResultRoute
  '/auth/verify-sent': typeof AuthVerifySentRoute
  '/wizard/branch': typeof WizardBranchRoute
  '/wizard/checklist': typeof WizardChecklistRoute
  '/wizard/company': typeof WizardCompanyRoute
  '/wizard/employee': typeof WizardEmployeeRoute
  '/wizard/financial': typeof WizardFinancialRoute
  '/wizard/org': typeof WizardOrgRoute
  '/wizard/position': typeof WizardPositionRoute
  '/wizard/review': typeof WizardReviewRoute
  '/wizard/success': typeof WizardSuccessRoute
  '/wizard/': typeof WizardIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/reference-data/$sourceId': typeof AuthenticatedAdminReferenceDataSourceIdRoute
  '/_authenticated/admin/business-partners/': typeof AuthenticatedAdminBusinessPartnersIndexRoute
  '/_authenticated/admin/languages/': typeof AuthenticatedAdminLanguagesIndexRoute
  '/_authenticated/admin/master-data/': typeof AuthenticatedAdminMasterDataIndexRoute
  '/_authenticated/admin/numbering/': typeof AuthenticatedAdminNumberingIndexRoute
  '/_authenticated/admin/organization/': typeof AuthenticatedAdminOrganizationIndexRoute
  '/_authenticated/admin/reference-data/': typeof AuthenticatedAdminReferenceDataIndexRoute
  '/_authenticated/admin/security/': typeof AuthenticatedAdminSecurityIndexRoute
  '/_authenticated/admin/system/': typeof AuthenticatedAdminSystemIndexRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/workflow/': typeof AuthenticatedAdminWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/language'
    | '/setup-landing'
    | '/wizard'
    | '/admin'
    | '/app/dashboard'
    | '/auth/create-password'
    | '/auth/email'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/verify-result'
    | '/auth/verify-sent'
    | '/wizard/branch'
    | '/wizard/checklist'
    | '/wizard/company'
    | '/wizard/employee'
    | '/wizard/financial'
    | '/wizard/org'
    | '/wizard/position'
    | '/wizard/review'
    | '/wizard/success'
    | '/wizard/'
    | '/admin/'
    | '/admin/reference-data/$sourceId'
    | '/admin/business-partners/'
    | '/admin/languages/'
    | '/admin/master-data/'
    | '/admin/numbering/'
    | '/admin/organization/'
    | '/admin/reference-data/'
    | '/admin/security/'
    | '/admin/system/'
    | '/admin/templates/'
    | '/admin/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/language'
    | '/setup-landing'
    | '/app/dashboard'
    | '/auth/create-password'
    | '/auth/email'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/verify-result'
    | '/auth/verify-sent'
    | '/wizard/branch'
    | '/wizard/checklist'
    | '/wizard/company'
    | '/wizard/employee'
    | '/wizard/financial'
    | '/wizard/org'
    | '/wizard/position'
    | '/wizard/review'
    | '/wizard/success'
    | '/wizard'
    | '/admin'
    | '/admin/reference-data/$sourceId'
    | '/admin/business-partners'
    | '/admin/languages'
    | '/admin/master-data'
    | '/admin/numbering'
    | '/admin/organization'
    | '/admin/reference-data'
    | '/admin/security'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/language'
    | '/setup-landing'
    | '/wizard'
    | '/_authenticated/admin'
    | '/app/dashboard'
    | '/auth/create-password'
    | '/auth/email'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/verify-result'
    | '/auth/verify-sent'
    | '/wizard/branch'
    | '/wizard/checklist'
    | '/wizard/company'
    | '/wizard/employee'
    | '/wizard/financial'
    | '/wizard/org'
    | '/wizard/position'
    | '/wizard/review'
    | '/wizard/success'
    | '/wizard/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/reference-data/$sourceId'
    | '/_authenticated/admin/business-partners/'
    | '/_authenticated/admin/languages/'
    | '/_authenticated/admin/master-data/'
    | '/_authenticated/admin/numbering/'
    | '/_authenticated/admin/organization/'
    | '/_authenticated/admin/reference-data/'
    | '/_authenticated/admin/security/'
    | '/_authenticated/admin/system/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LanguageRoute: typeof LanguageRoute
  SetupLandingRoute: typeof SetupLandingRoute
  WizardRoute: typeof WizardRouteWithChildren
  AuthCreatePasswordRoute: typeof AuthCreatePasswordRoute
  AuthEmailRoute: typeof AuthEmailRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyResultRoute: typeof AuthVerifyResultRoute
  AuthVerifySentRoute: typeof AuthVerifySentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-landing': {
      id: '/setup-landing'
      path: '/setup-landing'
      fullPath: '/setup-landing'
      preLoaderRoute: typeof SetupLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/'
      fullPath: '/wizard/'
      preLoaderRoute: typeof WizardIndexRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/success': {
      id: '/wizard/success'
      path: '/success'
      fullPath: '/wizard/success'
      preLoaderRoute: typeof WizardSuccessRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/review': {
      id: '/wizard/review'
      path: '/review'
      fullPath: '/wizard/review'
      preLoaderRoute: typeof WizardReviewRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/position': {
      id: '/wizard/position'
      path: '/position'
      fullPath: '/wizard/position'
      preLoaderRoute: typeof WizardPositionRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/org': {
      id: '/wizard/org'
      path: '/org'
      fullPath: '/wizard/org'
      preLoaderRoute: typeof WizardOrgRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/financial': {
      id: '/wizard/financial'
      path: '/financial'
      fullPath: '/wizard/financial'
      preLoaderRoute: typeof WizardFinancialRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/employee': {
      id: '/wizard/employee'
      path: '/employee'
      fullPath: '/wizard/employee'
      preLoaderRoute: typeof WizardEmployeeRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/company': {
      id: '/wizard/company'
      path: '/company'
      fullPath: '/wizard/company'
      preLoaderRoute: typeof WizardCompanyRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/checklist': {
      id: '/wizard/checklist'
      path: '/checklist'
      fullPath: '/wizard/checklist'
      preLoaderRoute: typeof WizardChecklistRouteImport
      parentRoute: typeof WizardRoute
    }
    '/wizard/branch': {
      id: '/wizard/branch'
      path: '/branch'
      fullPath: '/wizard/branch'
      preLoaderRoute: typeof WizardBranchRouteImport
      parentRoute: typeof WizardRoute
    }
    '/auth/verify-sent': {
      id: '/auth/verify-sent'
      path: '/auth/verify-sent'
      fullPath: '/auth/verify-sent'
      preLoaderRoute: typeof AuthVerifySentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-result': {
      id: '/auth/verify-result'
      path: '/auth/verify-result'
      fullPath: '/auth/verify-result'
      preLoaderRoute: typeof AuthVerifyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email': {
      id: '/auth/email'
      path: '/auth/email'
      fullPath: '/auth/email'
      preLoaderRoute: typeof AuthEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-password': {
      id: '/auth/create-password'
      path: '/auth/create-password'
      fullPath: '/auth/create-password'
      preLoaderRoute: typeof AuthCreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/workflow/': {
      id: '/_authenticated/admin/workflow/'
      path: '/workflow'
      fullPath: '/admin/workflow/'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system/': {
      id: '/_authenticated/admin/system/'
      path: '/system'
      fullPath: '/admin/system/'
      preLoaderRoute: typeof AuthenticatedAdminSystemIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/security/': {
      id: '/_authenticated/admin/security/'
      path: '/security'
      fullPath: '/admin/security/'
      preLoaderRoute: typeof AuthenticatedAdminSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reference-data/': {
      id: '/_authenticated/admin/reference-data/'
      path: '/reference-data'
      fullPath: '/admin/reference-data/'
      preLoaderRoute: typeof AuthenticatedAdminReferenceDataIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organization/': {
      id: '/_authenticated/admin/organization/'
      path: '/organization'
      fullPath: '/admin/organization/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/numbering/': {
      id: '/_authenticated/admin/numbering/'
      path: '/numbering'
      fullPath: '/admin/numbering/'
      preLoaderRoute: typeof AuthenticatedAdminNumberingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/master-data/': {
      id: '/_authenticated/admin/master-data/'
      path: '/master-data'
      fullPath: '/admin/master-data/'
      preLoaderRoute: typeof AuthenticatedAdminMasterDataIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/languages/': {
      id: '/_authenticated/admin/languages/'
      path: '/languages'
      fullPath: '/admin/languages/'
      preLoaderRoute: typeof AuthenticatedAdminLanguagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business-partners/': {
      id: '/_authenticated/admin/business-partners/'
      path: '/business-partners'
      fullPath: '/admin/business-partners/'
      preLoaderRoute: typeof AuthenticatedAdminBusinessPartnersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reference-data/$sourceId': {
      id: '/_authenticated/admin/reference-data/$sourceId'
      path: '/reference-data/$sourceId'
      fullPath: '/admin/reference-data/$sourceId'
      preLoaderRoute: typeof AuthenticatedAdminReferenceDataSourceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminReferenceDataSourceIdRoute: typeof AuthenticatedAdminReferenceDataSourceIdRoute
  AuthenticatedAdminBusinessPartnersIndexRoute: typeof AuthenticatedAdminBusinessPartnersIndexRoute
  AuthenticatedAdminLanguagesIndexRoute: typeof AuthenticatedAdminLanguagesIndexRoute
  AuthenticatedAdminMasterDataIndexRoute: typeof AuthenticatedAdminMasterDataIndexRoute
  AuthenticatedAdminNumberingIndexRoute: typeof AuthenticatedAdminNumberingIndexRoute
  AuthenticatedAdminOrganizationIndexRoute: typeof AuthenticatedAdminOrganizationIndexRoute
  AuthenticatedAdminReferenceDataIndexRoute: typeof AuthenticatedAdminReferenceDataIndexRoute
  AuthenticatedAdminSecurityIndexRoute: typeof AuthenticatedAdminSecurityIndexRoute
  AuthenticatedAdminSystemIndexRoute: typeof AuthenticatedAdminSystemIndexRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminWorkflowIndexRoute: typeof AuthenticatedAdminWorkflowIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminReferenceDataSourceIdRoute:
    AuthenticatedAdminReferenceDataSourceIdRoute,
  AuthenticatedAdminBusinessPartnersIndexRoute:
    AuthenticatedAdminBusinessPartnersIndexRoute,
  AuthenticatedAdminLanguagesIndexRoute: AuthenticatedAdminLanguagesIndexRoute,
  AuthenticatedAdminMasterDataIndexRoute:
    AuthenticatedAdminMasterDataIndexRoute,
  AuthenticatedAdminNumberingIndexRoute: AuthenticatedAdminNumberingIndexRoute,
  AuthenticatedAdminOrganizationIndexRoute:
    AuthenticatedAdminOrganizationIndexRoute,
  AuthenticatedAdminReferenceDataIndexRoute:
    AuthenticatedAdminReferenceDataIndexRoute,
  AuthenticatedAdminSecurityIndexRoute: AuthenticatedAdminSecurityIndexRoute,
  AuthenticatedAdminSystemIndexRoute: AuthenticatedAdminSystemIndexRoute,
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminWorkflowIndexRoute: AuthenticatedAdminWorkflowIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WizardRouteChildren {
  WizardBranchRoute: typeof WizardBranchRoute
  WizardChecklistRoute: typeof WizardChecklistRoute
  WizardCompanyRoute: typeof WizardCompanyRoute
  WizardEmployeeRoute: typeof WizardEmployeeRoute
  WizardFinancialRoute: typeof WizardFinancialRoute
  WizardOrgRoute: typeof WizardOrgRoute
  WizardPositionRoute: typeof WizardPositionRoute
  WizardReviewRoute: typeof WizardReviewRoute
  WizardSuccessRoute: typeof WizardSuccessRoute
  WizardIndexRoute: typeof WizardIndexRoute
}

const WizardRouteChildren: WizardRouteChildren = {
  WizardBranchRoute: WizardBranchRoute,
  WizardChecklistRoute: WizardChecklistRoute,
  WizardCompanyRoute: WizardCompanyRoute,
  WizardEmployeeRoute: WizardEmployeeRoute,
  WizardFinancialRoute: WizardFinancialRoute,
  WizardOrgRoute: WizardOrgRoute,
  WizardPositionRoute: WizardPositionRoute,
  WizardReviewRoute: WizardReviewRoute,
  WizardSuccessRoute: WizardSuccessRoute,
  WizardIndexRoute: WizardIndexRoute,
}

const WizardRouteWithChildren =
  WizardRoute._addFileChildren(WizardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LanguageRoute: LanguageRoute,
  SetupLandingRoute: SetupLandingRoute,
  WizardRoute: WizardRouteWithChildren,
  AuthCreatePasswordRoute: AuthCreatePasswordRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyResultRoute: AuthVerifyResultRoute,
  AuthVerifySentRoute: AuthVerifySentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
